# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

premultiply_list_of_matrices <- function(Qt, X_list) {
    .Call('_GridLMM_premultiply_list_of_matrices', PACKAGE = 'GridLMM', Qt, X_list)
}

F_hats <- function(beta_hats, RSSs, V_star_L, n, b, m) {
    .Call('_GridLMM_F_hats', PACKAGE = 'GridLMM', beta_hats, RSSs, V_star_L, n, b, m)
}

log_det_of_XtX <- function(X_cov, X_tests, X_indices) {
    .Call('_GridLMM_log_det_of_XtX', PACKAGE = 'GridLMM', X_cov, X_tests, X_indices)
}

GridLMM_SS_dense_c <- function(Y, inv_chol_Vi_transpose, X_cov, X_tests, X_indices, inv_prior_X, V_log_det) {
    .Call('_GridLMM_GridLMM_SS_dense_c', PACKAGE = 'GridLMM', Y, inv_chol_Vi_transpose, X_cov, X_tests, X_indices, inv_prior_X, V_log_det)
}

GridLMM_SS_sparse_c <- function(Y, inv_chol_Vi_transpose, X_cov, X_tests, X_indices, inv_prior_X, V_log_det) {
    .Call('_GridLMM_GridLMM_SS_sparse_c', PACKAGE = 'GridLMM', Y, inv_chol_Vi_transpose, X_cov, X_tests, X_indices, inv_prior_X, V_log_det)
}

GridLMM_SS_downdate <- function(Y, V_inv, X_cov, X_tests, inv_prior_X, downdate_weights, downdate_Xs, X_indices, V_log_det) {
    .Call('_GridLMM_GridLMM_SS_downdate', PACKAGE = 'GridLMM', Y, V_inv, X_cov, X_tests, inv_prior_X, downdate_weights, downdate_Xs, X_indices, V_log_det)
}

