# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridLMM_SS_cisQTL <- function(Y, chol_Vi_R_, X_cov, X, X_indices, downdate_Xs, downdate_weights, inv_prior_X) {
    .Call('_GridLMM_GridLMM_SS_cisQTL', PACKAGE = 'GridLMM', Y, chol_Vi_R_, X_cov, X, X_indices, downdate_Xs, downdate_weights, inv_prior_X)
}

svd_c <- function(X) {
    .Call('_GridLMM_svd_c', PACKAGE = 'GridLMM', X)
}

chol_c <- function(X) {
    .Call('_GridLMM_chol_c', PACKAGE = 'GridLMM', X)
}

premultiply_list_of_matrices <- function(Qt_, X_list) {
    .Call('_GridLMM_premultiply_list_of_matrices', PACKAGE = 'GridLMM', Qt_, X_list)
}

chol_update_L <- function(L, X, weights) {
    .Call('_GridLMM_chol_update_L', PACKAGE = 'GridLMM', L, X, weights)
}

chol_update <- function(L, X, sign) {
    .Call('_GridLMM_chol_update', PACKAGE = 'GridLMM', L, X, sign)
}

chol_dropRows <- function(L, start_row, num_rows) {
    .Call('_GridLMM_chol_dropRows', PACKAGE = 'GridLMM', L, start_row, num_rows)
}

crossprod_cholR <- function(chol_R, X) {
    .Call('_GridLMM_crossprod_cholR', PACKAGE = 'GridLMM', chol_R, X)
}

F_hats <- function(beta_hats, RSSs, V_star_L, n, b, m) {
    .Call('_GridLMM_F_hats', PACKAGE = 'GridLMM', beta_hats, RSSs, V_star_L, n, b, m)
}

log_det_of_XtX <- function(X_cov, X_tests, X_indices) {
    .Call('_GridLMM_log_det_of_XtX', PACKAGE = 'GridLMM', X_cov, X_tests, X_indices)
}

GridLMM_SS_matrix <- function(Y, chol_Vi_R_, X_cov, X_list_, X_indices, inv_prior_X) {
    .Call('_GridLMM_GridLMM_SS_matrix', PACKAGE = 'GridLMM', Y, chol_Vi_R_, X_cov, X_list_, X_indices, inv_prior_X)
}

build_downdate_Xs <- function(RE_index, X_list_, proximal_markers, active_X_list) {
    .Call('_GridLMM_build_downdate_Xs', PACKAGE = 'GridLMM', RE_index, X_list_, proximal_markers, active_X_list)
}

GridLMM_SS_downdate_matrix <- function(Y, chol_Vi_R, X_cov, X_list_, X_indices, downdate_Xs, downdate_weights, inv_prior_X) {
    .Call('_GridLMM_GridLMM_SS_downdate_matrix', PACKAGE = 'GridLMM', Y, chol_Vi_R, X_cov, X_list_, X_indices, downdate_Xs, downdate_weights, inv_prior_X)
}

f <- function(x) {
    .Call('_GridLMM_f', PACKAGE = 'GridLMM', x)
}

min_f <- function() {
    .Call('_GridLMM_min_f', PACKAGE = 'GridLMM')
}

GridLMM_test_setTest <- function(Y, chol_Vi_R, G, X, tolerance = 0.01) {
    .Call('_GridLMM_GridLMM_test_setTest', PACKAGE = 'GridLMM', Y, chol_Vi_R, G, X, tolerance)
}

GridLMM_setTest_downdate_matrix <- function(Y, chol_Vi_R, X_cov, X, X_indices, downdate_Xs, downdate_weights, inv_prior_X, tolerance = 0.01) {
    .Call('_GridLMM_GridLMM_setTest_downdate_matrix', PACKAGE = 'GridLMM', Y, chol_Vi_R, X_cov, X, X_indices, downdate_Xs, downdate_weights, inv_prior_X, tolerance)
}

GridLMM_test_setTest2 <- function(Y, chol_Vi_R, G, X, tolerance = 0.01) {
    .Call('_GridLMM_GridLMM_test_setTest2', PACKAGE = 'GridLMM', Y, chol_Vi_R, G, X, tolerance)
}

